### ISSUE TITLE
About page 

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/newgraphenvironment.github.io#6]
- remove the sidebar and add a photo?
- add link to projects page through featured projects section https://hugo-apero-docs.netlify.app/learn/about-page/#set-up-the-main-section

**Comment by NewGraphEnvironment** [comment]
1. remove the sidebar - ya - sounds good
2. Link to projects page... Is this Q regarding links to individual project descriptions through sections in the "Projects" tab?  If so yes. Template setup looks good for that.

![image](https://github.com/NewGraphEnvironment/newgraphenvironment.github.io/assets/46538103/a252d848-d776-410c-8867-f22705b7c1e1)

**Comment by lucy-schick** [comment]
1. So keep the sidebar?
2. I was actually referring to the about page because we have the option to add links to certain pages through "featured content". Was thinking of setting one of "the featured items" to projects so it will take people to the projects page

![Screen Shot 2023-12-19 at 8 06 36 AM](https://github.com/NewGraphEnvironment/newgraphenvironment.github.io/assets/151881303/4b36d987-bb0a-408f-898e-2f1fd0d5c7d0)

**Comment by NewGraphEnvironment** [comment]
- [x] add interactive model - couldn't replace main landing photo so put in  "read more".  used this https://discourse.gohugo.io/t/how-to-use-iframe-content-correctly-in-a-yaml-file/14360/3
- [x] customize interests
- [x] change avatar
- [x] link to Ktunaxa language sound clip

will close with commit. can reopen with plans for next moves

**Comment by NewGraphEnvironment** [comment]
didn't close automatically because default branch was not yet `dev`.  it is now
